### ISSUE TITLE
Smarter search of user names with telega-chat-with

### ISSUE THREAD

**Issue by 4DA** [zevlg/telega.el#101]
Suppose some of you buddies username has "anon".
Your current input method is russian-typewriter and you call 'telega-chat-with
I want to be able to match him by either typing "анон" or "фтщт".

Same thing if you contact is named "анон", i want to be able to match him by typing anon if my input method is english.

So idea is that I don't switch input methods just for selecting a chat dialogue.

**Comment by zevlg** [comment]
You can press `s` in root buffer to perform global search using TDLib and telegram cloud instead of Emacs, it searches contacts, known chats, messages and unknown public chats. It supports queries in translit

**Comment by zevlg** [comment]
Could be done by installing post-command hook in minibuffer and call `telega--searchChats` on every command.

**Comment by zevlg** [comment]
I did some investigation on this.  It is hardly doable in current Emacs completion system.  Emacs does have [Programmed Completions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Programmed-Completion.html), however nature of `all-completions` have no custom matcher, it just uses string regexp to match.  So there is no way to match "anon" with "анон"

- `ido` does not have "Programmable Completions" interface.
- `ivy` does not work since it uses `all-completions`

Any other options?

**Comment by 4DA** [comment]
helm has something, i can take a look

**Comment by zevlg** [comment]
Very hard to done it right. Reopen if you have any ideas how this could be done nicely
